### ISSUE TITLE
Nokogiriでの実装

### ISSUE THREAD

**Issue by sinsnk** [sinsnk/get_news#1]
# 対象GEM

https://github.com/sparklemotion/nokogiri
※日本語にも対応すること→事前に日本語をエンコードしてNokogiriでGETリクエストがパースできるか確認する
- [ ] 引数として渡された文字列(args1)をRSSのURLにGETリクエストし、結果をNokogiriでパースし、対応するニュースのタイトルを引数として渡された件数(args2)取得する
- [ ] 引数の文字列に日本語対応をさせる
- [ ] 引数に対応するバリデーションを整備

```
@param [String] search_word: 検索文字列(単数)
@param [int] news_count: 取得したいニュースタイトル数
@return [String[]] ニュースタイトルを{news_count}で指定した数
get_news(search_word, news_count)
```
# ブランチ名

iss_1

**Comment by sinsnk** [comment]
メモ
http://morizyun.github.io/blog/ruby-nokogiri-scraping-tutorial/

**Comment by sinsnk** [comment]
エラー原因

```
Could not find gem 'open-uri (>= 0) ruby' in any of the gem sources listed in your Gemfile or
available on this machine.
```

http://stackoverflow.com/questions/20544662/unable-to-bundle-install-open-uri

**Comment by sinsnk** [comment]
https://news.google.com/news?ned=us&ie=UTF-8&oe=UTF-8&q=&output=atom&num=30&hl=ja

**Comment by hkamatsuka** [comment]
XMLだと書き方違うみたいです。

doc = Nokogiri::XML(open(url))
text = ""
doc.css("title").each do |elm|
  text += elm.content + "\n"
end

**Comment by sinsnk** [comment]
確認しました。
